/run/initialize

/vis/open OGL 600x600-0+0

/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/set/autoRefresh true

/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

# Axes, scale, etc.                                      ##changes are made from here
/vis/scene/add/scale 10 cm   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
